'use client';
import React, { useState, useCallback } from 'react';
import { useMBA } from '@/context/MBAContext';
import type { SCAMPERItem } from '@/types/mba';

const SCAMPER_CATEGORIES: { key: string; icon: string; label: string; prompt: string }[] = [
  {
    key: 'substitute',
    icon: '🔄',
    label: 'Substitute',
    prompt: 'What materials, resources, processes, or people can be substituted to improve?',
  },
  {
    key: 'combine',
    icon: '🧩',
    label: 'Combine',
    prompt: 'What can be combined — products, purposes, or synergies — to create something new?',
  },
  {
    key: 'adapt',
    icon: '🔧',
    label: 'Adapt',
    prompt: 'What existing ideas, products, or processes from other domains can be adapted?',
  },
  {
    key: 'modify',
    icon: '✏️',
    label: 'Modify',
    prompt: 'What can be modified — changed in scale, shape, form, or function?',
  },
  {
    key: 'put_to_another_use',
    icon: '🔀',
    label: 'Put to Another Use',
    prompt: 'How can the existing product, knowledge, or asset be used in a different context?',
  },
  {
    key: 'eliminate',
    icon: '🗑️',
    label: 'Eliminate',
    prompt: 'What features, steps, or components can be removed, simplified, or reduced?',
  },
  {
    key: 'reverse',
    icon: '🔁',
    label: 'Reverse',
    prompt: 'What happens if you reverse the process, sequence, or perspective?',
  },
];

function generateId(): string {
  return `scamper_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
}

export default function Ch16SCAMPER() {
  const { state, updateChapter } = useMBA();
  const scamperItems = state.chapter16.scamper;

  const [editTexts, setEditTexts] = useState<Record<string, string>>({});
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const getItemsForCategory = (category: string) =>
    scamperItems.filter((item) => item.category === category);

  const addIdea = useCallback(
    (category: string) => {
      const text = (editTexts[category] || '').trim();
      if (!text) return;
      const newItem: SCAMPERItem = { id: generateId(), category, idea: text };
      updateChapter('chapter16', { scamper: [...scamperItems, newItem] });
      setEditTexts((prev) => ({ ...prev, [category]: '' }));
    },
    [editTexts, scamperItems, updateChapter]
  );

  const removeIdea = useCallback(
    (id: string) => {
      updateChapter('chapter16', {
        scamper: scamperItems.filter((item) => item.id !== id),
      });
    },
    [scamperItems, updateChapter]
  );

  const totalIdeas = scamperItems.length;

  const generateMarkdown = useCallback(() => {
    let md = `# SCAMPER Brainstorming Report\n\n`;
    const categories = SCAMPER_CATEGORIES.map((c) => c.key);
    for (const key of categories) {
      const cat = SCAMPER_CATEGORIES.find((c) => c.key === key)!;
      const items = getItemsForCategory(key);
      md += `## ${cat.icon} ${cat.label}\n\n`;
      if (items.length === 0) {
        md += `_No ideas recorded._\n\n`;
      } else {
        items.forEach((item, idx) => {
          md += `${idx + 1}. ${item.idea}\n`;
        });
        md += `\n`;
      }
    }
    md += `---\n_Generated by The Visual MBA — SCAMPER Tool_\n`;
    return md;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [scamperItems]);

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdown());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback
      const ta = document.createElement('textarea');
      ta.value = generateMarkdown();
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // ─── NEW: Random Idea Generator ──────────────────────────────
  const [randomCategory, setRandomCategory] = useState<string | null>(null);
  const [randomPrompt, setRandomPrompt] = useState('');
  const [randomIdeaInput, setRandomIdeaInput] = useState('');

  const generateRandomPrompt = () => {
    const idx = Math.floor(Math.random() * SCAMPER_CATEGORIES.length);
    const cat = SCAMPER_CATEGORIES[idx];
    setRandomCategory(cat.key);
    setRandomPrompt(cat.prompt);
    setRandomIdeaInput('');
  };

  const addRandomIdea = () => {
    if (!randomCategory || !randomIdeaInput.trim()) return;
    addIdea(randomCategory);
    setRandomIdeaInput('');
    setRandomCategory(null);
    setRandomPrompt('');
  };

  // ─── NEW: Notes per idea ──────────────────────────────────────
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [showNoteInput, setShowNoteInput] = useState<string | null>(null);
  const [noteText, setNoteText] = useState('');

  const toggleNote = (id: string) => {
    if (showNoteInput === id) {
      setShowNoteInput(null);
      setNoteText('');
    } else {
      setShowNoteInput(id);
      setNoteText(notes[id] || '');
    }
  };

  const saveNote = (id: string) => {
    setNotes(prev => ({ ...prev, [id]: noteText }));
    setShowNoteInput(null);
    setNoteText('');
  };

  return (
    <div className="space-y-6 p-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="space-y-1">
        <h2 className="text-xl font-bold text-slate-900 dark:text-white">
          💡 SCAMPER Brainstorming
        </h2>
        <p className="text-slate-500 dark:text-slate-400 text-base">
          Explore 7 creative thinking techniques to generate innovative ideas.
          Type your thoughts in each category and export them as Markdown.
        </p>
      </div>

      {/* Top stats + export */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800/80 p-4 rounded-xl shadow-sm">
        <p className="text-base font-semibold text-slate-500 dark:text-slate-400">
          {totalIdeas} idea{totalIdeas !== 1 ? 's' : ''} recorded across{' '}
          {SCAMPER_CATEGORIES.length} categories
        </p>
        <button
          onClick={copyToClipboard}
          className="px-4 py-1.5 text-base font-semibold rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm transition-colors flex items-center gap-1.5 cursor-pointer"
        >
          {copied ? (
            <>✅ Copied!</>
          ) : (
            <>
              <span>📋</span> Export as Markdown
            </>
          )}
        </button>
      </div>

      {/* ─── NEW: Random Idea Generator ───────────────────────────── */}
      <div className="bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800/80 p-5 rounded-xl shadow-sm space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold uppercase tracking-wider text-slate-400 dark:text-slate-550">
            🎲 Random Idea Generator
          </h3>
          <button
            onClick={generateRandomPrompt}
            className="px-3 py-1.5 text-base font-semibold rounded-lg bg-amber-600 hover:bg-amber-700 text-white shadow-sm transition-colors cursor-pointer"
          >
            Generate Random
          </button>
        </div>
        {randomPrompt && (
          <div className="space-y-2">
            <p className="text-base text-slate-500 dark:text-slate-400 italic font-medium">{randomPrompt}</p>
            <div className="flex gap-2">
              <input
                type="text"
                value={randomIdeaInput}
                onChange={(e) => setRandomIdeaInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addRandomIdea()}
                placeholder="Type your idea..."
                className="flex-1 px-3 py-1.5 text-base rounded-lg bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-850 text-slate-900 dark:text-slate-100 placeholder-slate-400 dark:placeholder-slate-650 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-all"
              />
              <button
                onClick={addRandomIdea}
                disabled={!randomIdeaInput.trim()}
                className="px-4 py-1.5 text-base font-bold rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white disabled:opacity-40 disabled:cursor-not-allowed transition-colors cursor-pointer"
              >
                Add Idea
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Category cards */}
      <div className="grid grid-cols-1 grid-cols-1 md:grid-cols-2 gap-4">
        {SCAMPER_CATEGORIES.map((cat) => {
          const items = getItemsForCategory(cat.key);
          const isExpanded = activeCategory === cat.key;

          return (
            <div
              key={cat.key}
              className={`bg-white dark:bg-slate-900/40 rounded-xl border ${
                isExpanded ? 'border-emerald-500 shadow-md shadow-emerald-500/5' : 'border-slate-200 dark:border-slate-800/80'
              } overflow-hidden transition-all duration-200 shadow-sm`}
            >
              {/* Card header */}
              <button
                onClick={() =>
                  setActiveCategory(isExpanded ? null : cat.key)
                }
                className="w-full flex items-center justify-between p-4 hover:bg-slate-50/50 dark:hover:bg-slate-900/40 transition-colors cursor-pointer"
              >
                <div className="flex items-center gap-3">
                  <span className="text-xl">{cat.icon}</span>
                  <div className="text-left">
                    <h4 className="text-base font-semibold text-slate-850 dark:text-slate-200">
                      {cat.label}
                    </h4>
                    <p className="text-base text-slate-450 dark:text-slate-500 mt-0.5 font-medium">
                      {items.length} idea{items.length !== 1 ? 's' : ''}
                    </p>
                  </div>
                </div>
                <span className="text-slate-400 dark:text-slate-500 text-base font-bold">
                  {isExpanded ? '▲' : '▼'}
                </span>
              </button>

              {/* Expanded content */}
              {isExpanded && (
                <div className="px-4 pb-4 space-y-3 border-t border-slate-100 dark:border-slate-850 pt-3">
                  <p className="text-base text-slate-500 dark:text-slate-450 italic leading-relaxed font-medium">
                    {cat.prompt}
                  </p>

                  {/* Input area */}
                  <div className="flex gap-2">
                    <textarea
                      placeholder="Type your idea here..."
                      value={editTexts[cat.key] || ''}
                      onChange={(e) =>
                        setEditTexts((prev) => ({
                          ...prev,
                          [cat.key]: e.target.value,
                        }))
                      }
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !e.shiftKey) {
                          e.preventDefault();
                          addIdea(cat.key);
                        }
                      }}
                      rows={2}
                      className="flex-1 px-3 py-1.5 text-base rounded-lg bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-850 text-slate-900 dark:text-slate-100 placeholder-slate-450 focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-all resize-none"
                    />
                  </div>
                  <button
                    onClick={() => addIdea(cat.key)}
                    disabled={!(editTexts[cat.key] || '').trim()}
                    className="w-full py-1.5 text-base font-bold rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white disabled:opacity-40 disabled:cursor-not-allowed transition-colors cursor-pointer"
                  >
                    + Add Idea
                  </button>

                  {/* Existing ideas */}
                  {items.length > 0 && (
                    <div className="space-y-1.5 max-h-48 overflow-y-auto">
                      {items.map((item) => (
                        <div
                          key={item.id}
                          className="group flex flex-col gap-1 px-3 py-2 rounded-lg bg-slate-50 dark:bg-slate-950/40 border border-slate-100 dark:border-slate-850"
                        >
                          <div className="flex items-start gap-2 text-base text-slate-700 dark:text-slate-350">
                            <span className="text-emerald-500 font-bold mt-[1px] shrink-0">
                              •
                            </span>
                            <span className="flex-1 leading-relaxed font-medium">
                              {item.idea}
                            </span>
                            <div className="flex gap-1 shrink-0">
                              <button
                                onClick={() => toggleNote(item.id)}
                                className={`text-base px-1.5 py-0.5 rounded border transition-all cursor-pointer ${
                                  notes[item.id]
                                    ? 'bg-blue-50 border-blue-200 text-blue-600 dark:bg-blue-955/10 dark:border-blue-900/50 dark:text-blue-400'
                                    : 'bg-slate-100 border-slate-200 text-slate-400 dark:bg-slate-850 dark:border-slate-700 dark:text-slate-500'
                                }`}
                                title={notes[item.id] ? 'Edit note' : 'Add note'}
                              >
                                {notes[item.id] ? '📝' : '➕'}
                              </button>
                              <button
                                onClick={() => removeIdea(item.id)}
                                className="opacity-0 group-hover:opacity-100 text-slate-400 hover:text-red-500 transition-all cursor-pointer"
                                title="Remove idea"
                              >
                                ✕
                              </button>
                            </div>
                          </div>
                          {/* Note input / display */}
                          {showNoteInput === item.id ? (
                            <div className="flex gap-2 ml-5">
                              <input
                                type="text"
                                value={noteText}
                                onChange={(e) => setNoteText(e.target.value)}
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter') saveNote(item.id);
                                  if (e.key === 'Escape') toggleNote(item.id);
                                }}
                                placeholder="Add a note..."
                                className="flex-1 px-2 py-1 text-base rounded bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-850 text-slate-700 dark:text-slate-300 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                                autoFocus
                              />
                              <button onClick={() => saveNote(item.id)} className="text-base font-bold text-emerald-600 hover:text-emerald-700 px-1 cursor-pointer">✓</button>
                              <button onClick={() => toggleNote(item.id)} className="text-base font-bold text-slate-400 hover:text-red-500 px-1 cursor-pointer">✕</button>
                            </div>
                          ) : notes[item.id] ? (
                            <div className="ml-5 text-base text-slate-450 dark:text-slate-500 font-medium italic border-l-2 border-blue-200 dark:border-blue-900/50 pl-2">
                              {notes[item.id]}
                            </div>
                          ) : null}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Markdown preview */}
      {totalIdeas > 0 && (
        <details className="bg-white dark:bg-slate-900/40 rounded-xl border border-slate-200 dark:border-slate-800/80 overflow-hidden shadow-sm">
          <summary className="px-4 py-3 text-base font-bold uppercase tracking-wider text-slate-400 dark:text-slate-550 cursor-pointer hover:bg-slate-50/50 dark:hover:bg-slate-900/40 transition-colors">
            📄 Preview Markdown Export
          </summary>
          <pre className="px-4 py-3 text-base text-slate-500 dark:text-slate-450 bg-slate-950 overflow-x-auto border-t border-slate-200 dark:border-slate-850 whitespace-pre-wrap font-mono leading-relaxed">
            {generateMarkdown()}
          </pre>
        </details>
      )}

      {/* Hint */}
      <div className="text-base text-slate-450 dark:text-slate-500 bg-white dark:bg-slate-900/20 rounded-xl border border-slate-200 dark:border-slate-800/80 p-4 font-medium leading-relaxed">
        <p>
          <strong>Tip:</strong> Click a category card to expand it and start
          brainstorming. Press <kbd className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-250 dark:border-slate-700 text-slate-655 dark:text-slate-300 font-mono text-base">Enter</kbd> to quickly add an idea, <kbd className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 border border-slate-250 dark:border-slate-700 text-slate-655 dark:text-slate-300 font-mono text-base">Shift+Enter</kbd> for a new line. Use the <strong>Export as Markdown</strong> button to copy all ideas in a formatted report.
        </p>
      </div>
    </div>
  );
}
